language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
before_install:
  - sudo pip install cpp-coveralls
before_script:
  - composer self-update
  - composer install
script: vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php && vendor/bin/phpunit --prepend xdebug-filter.php --coverage-clover build/logs/clover.xml --coverage-text
after_success:
  - cat build/logs/clover.xml
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/php-coveralls -v; fi;'
  - bash <(curl -s https://codecov.io/bash)

