language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
before_install:
  - sudo pip install cpp-coveralls
before_script:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt update -y
  - pecl install pcov
  - phpenv config-rm xdebug.ini
  - ini_file=$(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")  
  - echo "pcov.enabled=1" >> $ini_file
  - echo "pcov.directory=api" >> $ini_file
  - composer install
script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text
after_success:
  - php vendor/bin/php-coveralls -v
  - bash <(curl -s https://codecov.io/bash)

