name: Testing countrycity
on: [push]
jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        php-version: [7.2, 7.3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: find files
        run: ls -la
      - name: make install script excutable
        run: chmod a+x .github/workflows/install.sh
      - name: Set up php and composer
        run: .github/workflows/install.sh ${{ matrix.php-version }}
      - name: Install dependencies
        run: composer self-update && composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php && vendor/bin/phpunit --prepend xdebug-filter.php --coverage-clover build/logs/clover.xml --coverage-text
      - name: coveralls
        run: sh -c php vendor/bin/php-coveralls -v
      - name: codecov-umbrella
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/logs/clover.xml
          name: github-actions-codecov